// declaring element
const player = new Player()
const username = document.getElementById('username')
const registerForm = document.getElementById('registerForm')
const logoutForm = document.getElementById('logoutForm')
const startSection = document.getElementById('start')
const box1 = document.getElementById('box1')
const box2 = document.getElementById('box2')
const box3 = document.getElementById('box3')
const rewardImage = document.getElementById('imgReward')
const idPlayer = document.getElementById('idPlayer')
const started = document.getElementById('start')
const rewarded = document.getElementById('reward')
const toped = document.getElementById('top')
const navStart = document.getElementById('navStart')
const navReward = document.getElementById('navReward')
const textRegist = document.getElementById('textRegist')
const notif = document.getElementById('notif')